// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Use DIRECT_URL (non-pooled) for migrate so pg_advisory_lock works.
    // Falls back to DATABASE_URL for generate/studio where pooling is fine.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
