// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Match Next.js env precedence: .env.local wins over .env. The Prisma CLI only
// reads .env by default, so without this a real connection string in .env.local
// is invisible to `migrate` / `generate` / `studio` while the (often
// placeholder-filled) .env value is used instead.
loadEnv({ path: ".env" });
loadEnv({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Use DIRECT_URL (non-pooled) for migrate so pg_advisory_lock works.
    // Falls back to DATABASE_URL for generate/studio where pooling is fine.
    // GitHub Actions exposes an unset secret as an empty string. Nullish
    // coalescing treats that as a value, so Prisma received an empty URL and
    // never fell back to DATABASE_URL. Treat blank strings as absent.
    url: process.env["DIRECT_URL"]?.trim() || process.env["DATABASE_URL"],
  },
});
