import type { CodexCardDef, SeasonDef } from "./types";

/**
 * Season I — THE FIRST SIGNAL. Fifty cards: 30 drop from packs, 16 are earned
 * through Trials, 3 are hidden around the site and 1 lives only in the free
 * Initiation Pack. Order here is the collector number (S1 · 001–050).
 */
const CARDS: CodexCardDef[] = [
  // ── Pack · STATIC ──────────────────────────────────────────────────────────
  { slug: "s1-dead-air", title: "Dead Air", subtitle: "The pause between broadcasts", cardType: "GLITCH", rarity: "STATIC", obtain: "pack",
    flavour: "The silence between shows has a texture. Some nights it hums back.", abilities: ["Hush", "Buffer"], art: { motif: "bars", palette: "void" } },
  { slug: "s1-the-antenna", title: "The Antenna", subtitle: "Rooftop receiver", cardType: "SIGNAL", rarity: "STATIC", obtain: "pack",
    flavour: "Point it at the sky. Wait. Write down what comes through.", abilities: ["Tune In"], art: { motif: "antenna", palette: "frost" } },
  { slug: "s1-candle-stub", title: "Candle Stub", subtitle: "Last inch of wax", cardType: "RITUAL", rarity: "STATIC", obtain: "pack",
    flavour: "Burned down through a hundred late episodes. Still lit.", abilities: ["Small Light"], art: { motif: "candle", palette: "ember" } },
  { slug: "s1-screen-moth", title: "Screen Moth", subtitle: "Drawn to the glow", cardType: "ENTITY", rarity: "STATIC", obtain: "pack",
    flavour: "It finds every monitor left on after midnight.", abilities: ["Flutter", "Linger"], art: { motif: "moth", palette: "dusk" } },
  { slug: "s1-salt-circle", title: "Salt Circle", subtitle: "Unbroken boundary", cardType: "RITUAL", rarity: "STATIC", obtain: "pack",
    flavour: "Nothing crosses. Not even you, if you forget which side you're on.", abilities: ["Ward"], art: { motif: "ring", palette: "frost" } },
  { slug: "s1-bent-key", title: "Bent Key", subtitle: "Opens something", cardType: "RELIC", rarity: "STATIC", obtain: "pack",
    flavour: "It opens a door somewhere. Not this one.", abilities: ["Try the Lock"], art: { motif: "key", palette: "gold" } },
  { slug: "s1-last-tram-moon", title: "Last Tram Moon", subtitle: "After the timetable", cardType: "LOCATION", rarity: "STATIC", obtain: "pack",
    flavour: "It runs after the schedule ends, under a moon nobody else sees.", abilities: ["Late Route"], art: { motif: "moon", palette: "sea" } },
  { slug: "s1-napkin-eye", title: "Napkin Eye", subtitle: "Doodled sigil", cardType: "SYMBOL", rarity: "STATIC", obtain: "pack",
    flavour: "Drawn in biro during a long stream. It's still watching.", abilities: ["Notice"], art: { motif: "eye", palette: "void" } },

  // ── Pack · SIGNAL ──────────────────────────────────────────────────────────
  { slug: "s1-number-station", title: "Number Station", subtitle: "Seven four seven", cardType: "SIGNAL", rarity: "SIGNAL", obtain: "pack",
    flavour: "A voice reads numbers at 3am. Nobody admits to counting.", abilities: ["Encode", "Repeat"], art: { motif: "radio", palette: "toxic" } },
  { slug: "s1-the-loop", title: "The Loop", subtitle: "You've read this before", cardType: "GLITCH", rarity: "SIGNAL", obtain: "pack",
    flavour: "You have read this card before. You will read it again.", abilities: ["Recur"], art: { motif: "spiral", palette: "violet" } },
  { slug: "s1-hollow-moon", title: "Hollow Moon", subtitle: "Lit from inside", cardType: "LOCATION", rarity: "SIGNAL", obtain: "pack",
    flavour: "Tap it and it rings. Something moved in years ago.", abilities: ["Echo", "Tide Pull"], art: { motif: "moon", palette: "frost" } },
  { slug: "s1-the-listener", title: "The Listener", subtitle: "Headphones on, always", cardType: "VOICE", rarity: "SIGNAL", obtain: "pack",
    flavour: "Four thousand hours of archive in. Still finding new things.", abilities: ["Attune"], art: { motif: "wave", palette: "sea" } },
  { slug: "s1-crow-courier", title: "Crow Courier", subtitle: "Carries the gossip", cardType: "ENTITY", rarity: "SIGNAL", obtain: "pack",
    flavour: "It knows who said what, and it remembers who said it first.", abilities: ["Deliver", "Remember"], art: { motif: "bird", palette: "void" } },
  { slug: "s1-mirror-twin", title: "Mirror Twin", subtitle: "Left-handed you", cardType: "CIPHER", rarity: "SIGNAL", obtain: "pack",
    flavour: "Same face, other hand. It blinks a half-second late.", abilities: ["Reflect"], art: { motif: "mirror", palette: "rose" } },
  { slug: "s1-ashen-hand", title: "Ashen Hand", subtitle: "Palm read in soot", cardType: "RITUAL", rarity: "SIGNAL", obtain: "pack",
    flavour: "Every line on it points somewhere you haven't been yet.", abilities: ["Read Palms"], art: { motif: "hand", palette: "ember" } },

  // ── Pack · TRANSMISSION ───────────────────────────────────────────────────
  { slug: "s1-broadcast-tower", title: "Broadcast Tower", subtitle: "Red light, blinking", cardType: "LOCATION", rarity: "TRANSMISSION", obtain: "pack",
    flavour: "It sends. Nobody remembers switching it on.", abilities: ["Amplify", "Reach"], art: { motif: "tower", palette: "blood" } },
  { slug: "s1-serpent-cable", title: "Serpent Cable", subtitle: "Undersea line", cardType: "ENTITY", rarity: "TRANSMISSION", obtain: "pack",
    flavour: "The data runs under the ocean. So does the thing wrapped around it.", abilities: ["Coil", "Carry"], art: { motif: "serpent", palette: "toxic" } },
  { slug: "s1-static-hourglass", title: "Static Hourglass", subtitle: "Sand made of noise", cardType: "RELIC", rarity: "TRANSMISSION", obtain: "pack",
    flavour: "Turn it over and the buffering starts again.", abilities: ["Delay", "Reset"], art: { motif: "hourglass", palette: "gold" } },
  { slug: "s1-rose-chalice", title: "Rose Chalice", subtitle: "Filled at the séance", cardType: "RELIC", rarity: "TRANSMISSION", obtain: "pack",
    flavour: "Whoever drinks first tells the truth until sunrise.", abilities: ["Confess"], art: { motif: "chalice", palette: "rose" } },
  { slug: "s1-comet-omen", title: "Comet Omen", subtitle: "Seen once a lifetime", cardType: "PROPHECY", rarity: "TRANSMISSION", obtain: "pack",
    flavour: "It was there for one night. Chat saw it. The VOD didn't.", abilities: ["Portend", "Streak"], art: { motif: "comet", palette: "frost" } },
  { slug: "s1-lotus-engine", title: "Lotus Engine", subtitle: "Opens by degrees", cardType: "SYMBOL", rarity: "TRANSMISSION", obtain: "pack",
    flavour: "One petal per revelation. It has not finished opening.", abilities: ["Bloom"], art: { motif: "lotus", palette: "dusk" } },

  // ── Pack · ANOMALY ─────────────────────────────────────────────────────────
  { slug: "s1-unlit-door", title: "The Unlit Door", subtitle: "Behind the set", cardType: "LOCATION", rarity: "ANOMALY", obtain: "pack",
    flavour: "It's in the background of three episodes. It isn't in the building.", abilities: ["Threshold", "Vanish"], art: { motif: "door", palette: "violet" } },
  { slug: "s1-many-eyed-choir", title: "Many-Eyed Choir", subtitle: "Chat, awake at 4am", cardType: "ENTITY", rarity: "ANOMALY", obtain: "pack",
    flavour: "A thousand eyes, one opinion, zero sleep.", abilities: ["Swarm", "Witness"], art: { motif: "eyes", palette: "blood" } },
  { slug: "s1-skull-radio", title: "Skull Radio", subtitle: "Tuned to the dead", cardType: "GLITCH", rarity: "ANOMALY", obtain: "pack",
    flavour: "Mostly static. Occasionally, someone you used to know.", abilities: ["Séance", "Crackle"], art: { motif: "skull", palette: "toxic" } },
  { slug: "s1-drowned-bell", title: "Drowned Bell", subtitle: "Rings underwater", cardType: "RELIC", rarity: "ANOMALY", obtain: "pack",
    flavour: "You hear it in the shower. You hear it in the bath. You stop taking baths.", abilities: ["Toll", "Undertow"], art: { motif: "bell", palette: "sea" } },

  // ── Pack · ORACLE and above ───────────────────────────────────────────────
  { slug: "s1-pale-oracle", title: "The Pale Oracle", subtitle: "Masked, answering", cardType: "ORACLE", rarity: "ORACLE", obtain: "pack",
    flavour: "She answers every question. She never answers the one you asked.", abilities: ["Foresee", "Deflect"], art: { motif: "mask", palette: "frost" } },
  { slug: "s1-sun-behind-sun", title: "Sun Behind the Sun", subtitle: "The second dawn", cardType: "DEITY", rarity: "ORACLE", obtain: "pack",
    flavour: "Look past the light you know. There's another one, and it's looking back.", abilities: ["Radiate", "Reveal"], art: { motif: "sun", palette: "gold" } },
  { slug: "s1-the-codex", title: "The Codex", subtitle: "Every word, indexed", cardType: "RELIC", rarity: "LEGENDARY", obtain: "pack", maxSupply: 500,
    flavour: "Every episode, every guest, every quote. Written down so none of it gets lost.", abilities: ["Recall All", "Cross-Reference"], art: { motif: "book", palette: "gold" } },
  { slug: "s1-psyche-ascendant", title: "Psyche Ascendant", subtitle: "The soul takes wing", cardType: "DEITY", rarity: "MYTHIC", obtain: "pack", maxSupply: 150,
    flavour: "Every transformation starts as a mess in a cocoon.", abilities: ["Metamorphose", "Ascend"], art: { motif: "moth", palette: "violet" } },
  { slug: "s1-sky-eater", title: "The Signal That Ate the Sky", subtitle: "████ ██ ███", cardType: "GLITCH", rarity: "FORBIDDEN", obtain: "pack", maxSupply: 66,
    flavour: "It was a normal broadcast. Then the sky stopped rendering.", abilities: ["Consume", "Overwrite"], art: { motif: "eye", palette: "blood" } },

  // ── Initiation Pack exclusive ─────────────────────────────────────────────
  { slug: "s1-initiates-eye", title: "The Initiate's Eye", subtitle: "Season I founding sigil", cardType: "SYMBOL", rarity: "LEGENDARY", obtain: "signup",
    flavour: "Given once, to everyone who signed the book while the first signal was still live.", abilities: ["Witness the Beginning", "First Light"],
    art: { motif: "pyramid", palette: "gold" }, clue: "Given once, to every account that opens its Initiation Pack during Season I." },

  // ── Trials ────────────────────────────────────────────────────────────────
  { slug: "s1-kept-flame", title: "The Kept Flame", subtitle: "Favoured transmission", cardType: "RITUAL", rarity: "SIGNAL", obtain: "quest", questId: "favorite-1",
    flavour: "Keep one episode close and it keeps you warm.", abilities: ["Tend"], art: { motif: "flame", palette: "ember" },
    clue: "Keep one transmission close. The flame follows what you favour." },
  { slug: "s1-reliquary", title: "The Reliquary", subtitle: "Ten hearts, kept", cardType: "RELIC", rarity: "ANOMALY", obtain: "quest", questId: "favorite-10",
    flavour: "Ten favourites, kept like saints' bones in a gilded box.", abilities: ["Preserve", "Venerate"], art: { motif: "heart", palette: "gold" },
    clue: "Ten transmissions, kept like bones in a box." },
  { slug: "s1-first-word", title: "The First Word", subtitle: "Said out loud", cardType: "VOICE", rarity: "SIGNAL", obtain: "quest", questId: "comment-1",
    flavour: "Lurkers become cultists one comment at a time.", abilities: ["Speak Up"], art: { motif: "wave", palette: "rose" },
    clue: "Speak once, where others can hear you." },
  { slug: "s1-scribes-jar", title: "The Scribe's Jar", subtitle: "Five sayings, sealed", cardType: "RELIC", rarity: "TRANSMISSION", obtain: "quest", questId: "quotes-5",
    flavour: "Words worth keeping, pressed like flowers between glass.", abilities: ["Collect", "Quote"], art: { motif: "book", palette: "verdant" },
    clue: "Five sayings, sealed in glass. Save them as you find them." },
  { slug: "s1-pulse", title: "Pulse", subtitle: "A reaction, recorded", cardType: "SIGNAL", rarity: "STATIC", obtain: "quest", questId: "react-1",
    flavour: "The archive feels it every time you do.", abilities: ["Beat"], art: { motif: "heart", palette: "blood" },
    clue: "Let an episode feel your heartbeat." },
  { slug: "s1-seven-suns", title: "Seven Suns", subtitle: "A week of dawns", cardType: "PROPHECY", rarity: "ORACLE", obtain: "quest", questId: "streak-7",
    flavour: "Seven mornings in a row. The eighth feels different.", abilities: ["Persist", "Dawn"], art: { motif: "sun", palette: "ember" },
    clue: "Return for seven dawns in a row. Miss one and the count starts over." },
  { slug: "s1-the-unbroken", title: "The Unbroken", subtitle: "Ouroboros", cardType: "DEITY", rarity: "LEGENDARY", obtain: "quest", questId: "streak-30",
    flavour: "Thirty days. The serpent finally reaches its tail.", abilities: ["Endure", "Complete the Circle"], art: { motif: "serpent", palette: "gold" },
    clue: "Thirty days without a gap. The serpent must reach its own tail." },
  { slug: "s1-the-querent", title: "The Querent", subtitle: "One who asks", cardType: "ORACLE", rarity: "TRANSMISSION", obtain: "quest", questId: "reading-1",
    flavour: "The question matters more than the cards. The cards know that.", abilities: ["Ask", "Lay the Spread"], art: { motif: "star", palette: "violet" },
    clue: "Ask the deck a question and lay the cards out." },
  { slug: "s1-marginalia", title: "Marginalia", subtitle: "Ink in the gutter", cardType: "CIPHER", rarity: "SIGNAL", obtain: "quest", questId: "annotate-1",
    flavour: "The best part of any old book is what someone wrote beside it.", abilities: ["Annotate"], art: { motif: "hand", palette: "verdant" },
    clue: "Write in the margins of an episode. Leave an annotation." },
  { slug: "s1-salon-candle", title: "The Salon Candle", subtitle: "Lit for company", cardType: "RITUAL", rarity: "SIGNAL", obtain: "quest", questId: "salon-1",
    flavour: "Conversation goes deeper by candlelight.", abilities: ["Gather"], art: { motif: "candle", palette: "rose" },
    clue: "Bring a thought to the Salon." },
  { slug: "s1-cartographer", title: "The Cartographer", subtitle: "Maps the archive", cardType: "LOCATION", rarity: "TRANSMISSION", obtain: "quest", questId: "topics-3",
    flavour: "Every topic is a country. You've started drawing borders.", abilities: ["Chart", "Navigate"], art: { motif: "planet", palette: "sea" },
    clue: "Mark three territories on your map. Follow the topics you care about." },
  { slug: "s1-seekers-lens", title: "The Seeker's Lens", subtitle: "Always searching", cardType: "CIPHER", rarity: "SIGNAL", obtain: "quest", questId: "search-1",
    flavour: "Save the question and the archive keeps hunting for you.", abilities: ["Focus"], art: { motif: "eye", palette: "frost" },
    clue: "Keep a search so the archive remembers what you're hunting." },
  { slug: "s1-torn-foil", title: "Torn Foil", subtitle: "Wrapper confetti", cardType: "GLITCH", rarity: "ANOMALY", obtain: "quest", questId: "packs-5",
    flavour: "The best sound in the world is a pack tearing open.", abilities: ["Rip", "Shimmer"], art: { motif: "bars", palette: "rose" },
    clue: "Tear open five packs." },
  { slug: "s1-the-archivist", title: "The Archivist", subtitle: "Keeper of the set", cardType: "MEMBER", rarity: "ORACLE", obtain: "quest", questId: "collect-25",
    flavour: "Half the season in hand, and the roots go deeper every day.", abilities: ["Catalogue", "Keep"], art: { motif: "tree", palette: "verdant" },
    clue: "Hold twenty-five different cards from this season." },
  { slug: "s1-inner-circle", title: "The Inner Circle", subtitle: "Initiate+", cardType: "MEMBER", rarity: "ANOMALY", obtain: "quest", questId: "subscriber",
    flavour: "Inside the circle the signal comes through clearer.", abilities: ["Belong", "Double Credits"], art: { motif: "lotus", palette: "violet" },
    clue: "Join the Initiate+ circle." },
  { slug: "s1-oracles-crown", title: "The Oracle's Crown", subtitle: "Highest seat", cardType: "MEMBER", rarity: "MYTHIC", obtain: "quest", questId: "oracle-tier",
    flavour: "Worn by those who hold up the whole temple.", abilities: ["Reign", "Triple Credits"], art: { motif: "crown", palette: "gold" },
    clue: "Reach the Oracle tier." },

  // ── Secrets ───────────────────────────────────────────────────────────────
  { slug: "s1-lost-page", title: "The Lost Page", subtitle: "Torn from the index", cardType: "CIPHER", rarity: "ANOMALY", obtain: "secret",
    flavour: "Every archive has a page that points nowhere. This is what was on it.", abilities: ["Misdirect", "Find"], art: { motif: "book", palette: "void" },
    clue: "Where the map runs out, something was left behind." },
  { slug: "s1-footnote-ghost", title: "Footnote Ghost", subtitle: "Lives below the fold", cardType: "ENTITY", rarity: "ORACLE", obtain: "secret",
    flavour: "It haunts the smallest print on every page. It's lonely down there.", abilities: ["Haunt", "Whisper"], art: { motif: "mask", palette: "void" },
    clue: "Every page ends somewhere. Look at the very bottom." },
  { slug: "s1-seventh-knock", title: "The Seventh Knock", subtitle: "Someone answers", cardType: "RITUAL", rarity: "LEGENDARY", obtain: "secret",
    flavour: "Six knocks is a visitor. The seventh is an invitation.", abilities: ["Summon", "Enter"], art: { motif: "door", palette: "blood" },
    clue: "Knock seven times on the season's seal." },
];

export const SEASON_1: SeasonDef = {
  number: 1,
  numeral: "I",
  name: "The First Signal",
  tagline: "Fifty cards. Some you pull, some you earn, and three you have to find.",
  startsAt: "2026-09-22T00:00:00Z",
  endsAt: "2026-12-21T00:00:00Z",
  palette: "gold",
  cards: CARDS,
  packs: [
    {
      slug: "s1-booster",
      name: "First Signal Booster",
      description: "Five Season I cards. At least one is Signal rarity or better.",
      cost: 100,
      cardCount: 5,
      sortOrder: 1,
      artTheme: "frost",
      guaranteeRarity: "SIGNAL",
      weights: {
        weightStatic: 52, weightSignal: 28, weightTransmission: 13, weightAnomaly: 5,
        weightOracle: 1.4, weightLegendary: 0.45, weightMythic: 0.12, weightForbidden: 0.03,
      },
    },
    {
      slug: "s1-reliquary",
      name: "Reliquary Box",
      description: "Ten Season I cards with better odds. One Anomaly or better guaranteed.",
      cost: 400,
      cardCount: 10,
      sortOrder: 2,
      artTheme: "gold",
      guaranteeRarity: "ANOMALY",
      weights: {
        weightStatic: 35, weightSignal: 30, weightTransmission: 20, weightAnomaly: 10,
        weightOracle: 3.5, weightLegendary: 1.1, weightMythic: 0.3, weightForbidden: 0.1,
      },
    },
  ],
};
