import type { Metadata } from "next";
import Link from "next/link";
import { buildMetadata } from "@/lib/seo";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";

export const revalidate = 86400;

export const metadata: Metadata = buildMetadata({
  title: "How CultCodex Works — Methodology & Transparency",
  description:
    "How CultCodex generates summaries, character profiles, and archive content — and how to report inaccuracies.",
  path: "/about/methodology",
});

const SECTION_CLS = "border border-border rounded-lg bg-surface overflow-hidden";
const HEADING_CLS =
  "flex items-center gap-2 border-b border-border bg-elevated px-4 py-2.5";
const BODY_CLS = "px-4 py-4 space-y-3 text-sm text-text-primary leading-relaxed";

function SectionBlock({
  sigil,
  title,
  children,
}: {
  sigil: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className={SECTION_CLS}>
      <div className={HEADING_CLS}>
        <span className="font-mono text-xs text-accent-gold">{sigil}</span>
        <h2 className="font-mono text-[10px] uppercase tracking-[0.3em] font-semibold text-text-muted">
          {title}
        </h2>
      </div>
      <div className={BODY_CLS}>{children}</div>
    </div>
  );
}

export default function MethodologyPage() {
  return (
    <>
      <main className="mx-auto max-w-2xl px-4 py-8 space-y-6">
        <Breadcrumbs
          items={[
            { label: "CultCodex", href: "/" },
            { label: "About", href: "/about/methodology" },
            { label: "Methodology" },
          ]}
        />

        {/* Page header */}
        <div className="space-y-1">
          <p className="font-mono text-[9px] uppercase tracking-[0.4em] text-accent-violet">
            /// transparency_log
          </p>
          <h1 className="text-2xl font-bold text-text-primary">How CultCodex Works</h1>
          <p className="text-sm text-text-secondary leading-relaxed">
            CultCodex is a fan-built archive for the Cult of Psyche livestream universe. This page
            explains how content is sourced, where AI is involved, and how to flag errors.
          </p>
        </div>

        <SectionBlock sigil="◈" title="What CultCodex Is">
          <p>
            CultCodex is an independent fan archive — not an official Cult of Psyche publication.
            It indexes episodes, guests, lore, and topics from the @CultofPsyche and
            @PsychesNightmares YouTube channels to make the archive searchable and explorable.
          </p>
          <p>
            Episode metadata (titles, dates, thumbnails) is pulled directly from the YouTube API.
            Transcripts are fetched from YouTube&rsquo;s auto-generated captions where available.
          </p>
        </SectionBlock>

        <SectionBlock sigil="⬡" title="AI-Generated Content">
          <p>
            Several content types on CultCodex are generated by AI (Anthropic Claude) based on
            episode transcripts and metadata. These include:
          </p>
          <ul className="space-y-2 mt-1">
            {[
              "Episode summaries (short and long)",
              'Guest / character profiles ("Codex entries")',
              "Notable quotes extraction",
              "Lore entries and topic clusters",
              "Psychenomicon narrative chapters (explicitly mythic/symbolic interpretations)",
            ].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="text-accent-gold/60 shrink-0 mt-0.5">·</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p className="text-text-secondary">
            AI-generated content is clearly marked with a{" "}
            <span className="font-mono text-accent-violet text-xs">◈ AI-generated</span> notice
            wherever it appears.
          </p>
        </SectionBlock>

        <SectionBlock sigil="⚡" title="Important Limitations">
          <p className="font-medium text-text-secondary">
            AI summaries and character profiles describe on-stream discussion and performance
            personas — not verified real-world claims.
          </p>
          <ul className="space-y-2 mt-1">
            {[
              "Summaries are generated from transcripts and may misattribute statements or miss context.",
              "Character profiles reflect how someone appears across recorded streams, not their private life.",
              "AI models can hallucinate — descriptions may contain factual errors.",
              "Transcript accuracy varies: auto-generated captions sometimes mishear words or names.",
              "Psychenomicon chapters are explicitly symbolic/mythic interpretations, not factual reporting.",
            ].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="text-red-400/60 shrink-0 mt-0.5">·</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </SectionBlock>

        <SectionBlock sigil="◉" title="How to Report Errors">
          <p>
            If you find inaccurate, harmful, or outdated information, please use the correction form
            linked on every episode and person page.
          </p>
          <p>
            Typical turnaround for corrections is 1–3 days. For urgent removal requests (e.g.
            content that puts someone at risk), contact the site owner directly.
          </p>
          <div className="mt-2">
            <Link
              href="/suggest-correction"
              className="inline-flex items-center gap-1.5 rounded border border-accent-violet/30 bg-accent-violet/10 px-3 py-1.5 font-mono text-xs text-accent-violet hover:border-accent-violet/60 transition-colors"
            >
              <span>◈</span>
              <span>Suggest a Correction</span>
            </Link>
          </div>
        </SectionBlock>

        <SectionBlock sigil="◇" title="Data Sources">
          <ul className="space-y-2">
            {[
              { label: "Video metadata", source: "YouTube Data API v3" },
              { label: "Transcripts", source: "YouTube auto-generated captions via Supadata API" },
              { label: "AI enrichment", source: "Anthropic Claude (claude-haiku-4-5)" },
              { label: "Semantic search", source: "OpenAI text-embedding-3-small + pgvector" },
            ].map(({ label, source }) => (
              <li key={label} className="flex gap-3 text-sm">
                <span className="text-text-muted shrink-0 min-w-[120px]">{label}</span>
                <span className="text-text-secondary">{source}</span>
              </li>
            ))}
          </ul>
        </SectionBlock>

        <p className="text-[11px] text-text-muted font-mono text-center pt-2">
          Last updated: May 2026 · CultCodex is an independent fan project
        </p>
      </main>
    </>
  );
}
