import { prisma } from "@/lib/db";
import { embedOne, vectorLiteral } from "@/lib/embeddings";

export interface ConceptQuery {
  concept: string;
  /** Minimum cosine similarity to count this concept as matched (0–1). Default 0.6 */
  threshold?: number;
}

export interface SemanticResult {
  segmentId: string;
  episodeId: string;
  episodeSlug: string;
  episodeTitle: string;
  episodeNumber: number | null;
  airDate: Date | null;
  thumbnailUrl: string | null;
  startSeconds: number;
  endSeconds: number;
  speakerLabel: string | null;
  text: string;
  /** Sum of per-concept cosine similarities — higher = better overall match */
  score: number;
  /** Per-concept similarity scores, keyed by concept string */
  conceptScores: Record<string, number>;
}

/**
 * Multi-concept intersection semantic search.
 *
 * Strategy:
 * 1. CTE finds top-200 candidate segments by primary concept (HNSW index path).
 * 2. Re-score those 200 candidates against every concept.
 * 3. Filter: every concept must exceed its threshold.
 * 4. Rank by sum of similarities, return top `limit`.
 *
 * This avoids a full table scan — only the primary concept touches the HNSW index;
 * remaining concepts run as brute-force distance on the 200-row candidate set.
 */
export async function semanticSearch(
  concepts: ConceptQuery[],
  options: {
    limit?: number;
    eraDateStart?: Date;
    eraDateEnd?: Date;
  } = {}
): Promise<SemanticResult[]> {
  if (concepts.length === 0) return [];

  const { limit = 20 } = options;
  const defaultThreshold = 0.6;

  // Embed all concepts in parallel
  const vectors = await Promise.all(concepts.map((c) => embedOne(c.concept)));

  // Primary concept (index-accelerated candidate scan)
  const primaryVec = vectorLiteral(vectors[0]);

  // We'll pass vectors as literal strings — safe because they are pure numbers
  // generated by us, never from user input directly.

  // Build era date filter clause
  let eraFilterCte = "";
  if (options.eraDateStart || options.eraDateEnd) {
    const conditions: string[] = [];
    if (options.eraDateStart) {
      conditions.push(`e."airDate" >= '${options.eraDateStart.toISOString()}'`);
    }
    if (options.eraDateEnd) {
      conditions.push(`e."airDate" <= '${options.eraDateEnd.toISOString()}'`);
    }
    eraFilterCte = `AND ${conditions.join(" AND ")}`;
  }

  // Build per-concept score expressions and threshold filters
  // Each is: 1 - (embedding <=> '[...]'::vector)  (cosine similarity from cosine distance)
  const conceptScoreExprs = vectors.map(
    (vec, i) => `1 - (s."embedding" <=> '${vectorLiteral(vec)}'::vector) AS score_${i}`
  );
  const thresholdFilters = concepts.map(
    (c, i) => `1 - (s."embedding" <=> '${vectorLiteral(vectors[i])}'::vector) >= ${c.threshold ?? defaultThreshold}`
  );
  const totalScoreExpr = vectors.map((_, i) => `score_${i}`).join(" + ");
  const conceptScoreSelect = vectors.map((_, i) => `scored.score_${i}`).join(", ");
  const conceptScoreCast = vectors.map((_, i) => `scored.score_${i}::float`).join(", ");

  const sql = `
    WITH candidates AS (
      SELECT s.id
      FROM "TranscriptSegment" s
      JOIN "Episode" e ON s."episodeId" = e.id
      WHERE s.embedding IS NOT NULL
        AND e.status = 'published'
        ${eraFilterCte}
      ORDER BY s.embedding <=> '${primaryVec}'::vector
      LIMIT 200
    ),
    scored AS (
      SELECT
        s.id             AS "segmentId",
        s."episodeId",
        s."startSeconds",
        s."endSeconds",
        s."speakerLabel",
        s.text,
        e.slug           AS "episodeSlug",
        e.title          AS "episodeTitle",
        e."episodeNumber",
        e."airDate",
        e."thumbnailUrl",
        ${conceptScoreExprs.join(",\n        ")}
      FROM candidates c
      JOIN "TranscriptSegment" s ON s.id = c.id
      JOIN "Episode" e ON s."episodeId" = e.id
    )
    SELECT
      scored."segmentId",
      scored."episodeId",
      scored."episodeSlug",
      scored."episodeTitle",
      scored."episodeNumber",
      scored."airDate",
      scored."thumbnailUrl",
      scored."startSeconds",
      scored."endSeconds",
      scored."speakerLabel",
      scored.text,
      (${totalScoreExpr}) AS total_score,
      ${conceptScoreSelect}
    FROM scored
    WHERE ${thresholdFilters.join("\n      AND ")}
    ORDER BY total_score DESC
    LIMIT ${limit}
  `;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rows: any[] = await prisma.$queryRawUnsafe(sql);

  return rows.map((row) => {
    const conceptScores: Record<string, number> = {};
    concepts.forEach((c, i) => {
      conceptScores[c.concept] = Number(row[`score_${i}`]);
    });
    return {
      segmentId: row.segmentId,
      episodeId: row.episodeId,
      episodeSlug: row.episodeSlug,
      episodeTitle: row.episodeTitle,
      episodeNumber: row.episodeNumber ? Number(row.episodeNumber) : null,
      airDate: row.airDate ? new Date(row.airDate) : null,
      thumbnailUrl: row.thumbnailUrl ?? null,
      startSeconds: Number(row.startSeconds),
      endSeconds: Number(row.endSeconds),
      speakerLabel: row.speakerLabel ?? null,
      text: row.text,
      score: Number(row.total_score),
      conceptScores,
    };
  });
}
