-- Phase 2: Expand card system with new rarities, types, and pack fields

-- New Rarity values
ALTER TYPE "Rarity" ADD VALUE IF NOT EXISTS 'LEGENDARY';
ALTER TYPE "Rarity" ADD VALUE IF NOT EXISTS 'MYTHIC';
ALTER TYPE "Rarity" ADD VALUE IF NOT EXISTS 'FORBIDDEN';

-- New CardType values
ALTER TYPE "CardType" ADD VALUE IF NOT EXISTS 'RELIC';
ALTER TYPE "CardType" ADD VALUE IF NOT EXISTS 'ENTITY';
ALTER TYPE "CardType" ADD VALUE IF NOT EXISTS 'PROPHECY';
ALTER TYPE "CardType" ADD VALUE IF NOT EXISTS 'MEMBER';
ALTER TYPE "CardType" ADD VALUE IF NOT EXISTS 'GLITCH';
ALTER TYPE "CardType" ADD VALUE IF NOT EXISTS 'MAHAVIDYA';
ALTER TYPE "CardType" ADD VALUE IF NOT EXISTS 'AVATAR';
ALTER TYPE "CardType" ADD VALUE IF NOT EXISTS 'INCIDENT';

-- Card: add personality field
ALTER TABLE "Card" ADD COLUMN IF NOT EXISTS "personality" TEXT;

-- CardPack: add weight columns for new rarities + artTheme
ALTER TABLE "CardPack" ADD COLUMN IF NOT EXISTS "weightLegendary" DOUBLE PRECISION NOT NULL DEFAULT 0.5;
ALTER TABLE "CardPack" ADD COLUMN IF NOT EXISTS "weightMythic"    DOUBLE PRECISION NOT NULL DEFAULT 0.1;
ALTER TABLE "CardPack" ADD COLUMN IF NOT EXISTS "weightForbidden" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE "CardPack" ADD COLUMN IF NOT EXISTS "artTheme"        TEXT;
