#!/usr/bin/env bash
set -Eeuo pipefail

output="${1:-prisma/production-schema.sql}"
source_url="${DIRECT_URL:-${DATABASE_URL:-}}"

if [[ -z "$source_url" ]]; then
  echo "DIRECT_URL or DATABASE_URL is required" >&2
  exit 1
fi

for command in pg_dump psql; do
  command -v "$command" >/dev/null || {
    echo "$command is required" >&2
    exit 1
  }
done

mkdir -p "$(dirname "$output")"
temporary="$(mktemp "${TMPDIR:-/tmp}/cultcodex-schema.XXXXXX.sql")"
trap 'rm -f "$temporary"' EXIT

# A snapshot with failed/rolled-back migration records cannot bootstrap safely.
problem_migrations="$(
  psql "$source_url" -XAtq -v ON_ERROR_STOP=1 -c '
    SELECT count(*)
    FROM public."_prisma_migrations"
    WHERE finished_at IS NULL
       OR rolled_back_at IS NOT NULL
       OR logs IS NOT NULL;
  '
)"
if [[ "$problem_migrations" != "0" ]]; then
  echo "Refusing snapshot: _prisma_migrations has $problem_migrations failed, rolled-back, or logged row(s)." >&2
  exit 1
fi

{
  echo "-- CultCodex production schema snapshot"
  echo "-- Generated by scripts/dump-production-schema.sh"
  echo "-- Contains no application rows. Only Prisma migration metadata is included"
  echo "-- so prisma migrate deploy remains safe after a clean restore."
  echo
  pg_dump "$source_url" \
    --schema-only \
    --schema=public \
    --clean \
    --if-exists \
    --no-owner \
    --no-privileges \
    --no-security-labels
  echo
  echo "-- Prisma migration metadata (no application data)"
  pg_dump "$source_url" \
    --data-only \
    --table='public._prisma_migrations' \
    --column-inserts \
    --no-owner \
    --no-privileges
} > "$temporary"

if grep -En '^(COPY |INSERT INTO )' "$temporary" \
  | grep -Ev '^.*INSERT INTO public\."_prisma_migrations"'; then
  echo "Refusing snapshot: unexpected data statement detected" >&2
  exit 1
fi

if grep -Eni '(postgres(ql)?://|password=|sslpassword=)' "$temporary"; then
  echo "Refusing snapshot: possible credential material detected" >&2
  exit 1
fi

mv "$temporary" "$output"
trap - EXIT
echo "Wrote $output"
