#!/usr/bin/env bash
set -Eeuo pipefail

output="${1:-prisma/production-schema.sql}"
source_url="${DIRECT_URL:-${DATABASE_URL:-}}"

if [[ -z "$source_url" ]]; then
  echo "DIRECT_URL or DATABASE_URL is required" >&2
  exit 1
fi

for command in pg_dump psql; do
  command -v "$command" >/dev/null || {
    echo "$command is required" >&2
    exit 1
  }
done

mkdir -p "$(dirname "$output")"
temporary="$(mktemp "${TMPDIR:-/tmp}/cultcodex-schema.XXXXXX.sql")"
trap 'rm -f "$temporary"' EXIT

# Failed and rolled-back rows describe attempts, not the live schema. Excluding
# them also prevents a recovered database from inheriting a P3009 blocker.
excluded_migrations="$(
  psql "$source_url" -XAtq -v ON_ERROR_STOP=1 -c '
    SELECT count(*)
    FROM public."_prisma_migrations"
    WHERE finished_at IS NULL OR rolled_back_at IS NOT NULL;
  '
)"
if [[ "$excluded_migrations" != "0" ]]; then
  echo "Excluding $excluded_migrations failed or rolled-back migration attempt(s)." >&2
fi

{
  echo "-- CultCodex production schema snapshot"
  echo "-- Generated by scripts/dump-production-schema.sh"
  echo "-- Contains no application rows. Only successful Prisma migration metadata"
  echo "-- is included so prisma migrate deploy remains safe after a clean restore."
  echo
  pg_dump "$source_url" \
    --schema-only \
    --schema=public \
    --clean \
    --if-exists \
    --no-owner \
    --no-privileges \
    --no-security-labels
  echo
  echo "-- Successful Prisma migration metadata (no application data)"
  psql "$source_url" -XAtq -v ON_ERROR_STOP=1 -c '
    SELECT format(
      $$INSERT INTO public."_prisma_migrations"
        (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count)
        VALUES (%L, %L, %L, %L, NULL, NULL, %L, %L);$$,
      id, checksum, finished_at, migration_name, started_at, applied_steps_count
    )
    FROM public."_prisma_migrations"
    WHERE finished_at IS NOT NULL
      AND rolled_back_at IS NULL
    ORDER BY started_at, id;
  '
} > "$temporary"

# PostgreSQL 18 emits this session setting, but it is unknown to PostgreSQL 16.
# It does not describe a database object and is safe to remove for portability.
sed -i '/^SET transaction_timeout = 0;$/d' "$temporary"

if grep -En '^(COPY |INSERT INTO )' "$temporary" \
  | grep -Ev '^.*INSERT INTO public\."_prisma_migrations"'; then
  echo "Refusing snapshot: unexpected data statement detected" >&2
  exit 1
fi

if grep -Eni '(postgres(ql)?://|password=|sslpassword=)' "$temporary"; then
  echo "Refusing snapshot: possible credential material detected" >&2
  exit 1
fi

mv "$temporary" "$output"
trap - EXIT
echo "Wrote $output"
